/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.brenervalladares.vista;
import org.brenervalladares.controlador.ControlDePago;
import org.brenervalladares.modelo.Pagos;
/**
 *
 * @author Brener Valladares
 */
public class VistaPagos extends javax.swing.JInternalFrame {
    Pagos pagoAntiguo = new Pagos();
    Pagos pagoActualizado = new Pagos();
    ControlDePago controlador = new ControlDePago();
    /**
     * Creates new form VistaPagos
     */
    public VistaPagos() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        txtIdProveedor = new javax.swing.JTextField();
        txtIdPago = new javax.swing.JTextField();
        lblIdCliente = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtIdCliente = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        lblIdPago = new javax.swing.JLabel();
        lblIdProveedor = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMonto.setForeground(new java.awt.Color(0, 0, 0));
        lblMonto.setText("Monto");

        txtIdPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPagoActionPerformed(evt);
            }
        });

        lblIdCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblIdCliente.setText("Id cliente");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblIdPago.setForeground(new java.awt.Color(0, 0, 0));
        lblIdPago.setText("Id");

        lblIdProveedor.setForeground(new java.awt.Color(0, 0, 0));
        lblIdProveedor.setText("Id proveedor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMonto)
                        .addComponent(lblIdProveedor)
                        .addComponent(lblIdPago)
                        .addComponent(lblIdCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdPago, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtIdProveedor)
                            .addComponent(txtMonto)
                            .addComponent(txtIdCliente))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnActualizar)
                        .addGap(48, 48, 48)
                        .addComponent(btnEliminar)
                        .addGap(0, 55, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar)
                .addGap(35, 35, 35)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdPago)
                    .addComponent(txtIdPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCliente)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProveedor)
                    .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMonto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPagoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        pagoActualizado.setId_pago(Integer.parseInt(txtIdPago.getText()));
        pagoActualizado.setId_cliente(Integer.parseInt(txtIdCliente.getText()));
        pagoActualizado.setId_proveedor(Integer.parseInt(txtIdProveedor.getText()));
        pagoActualizado.setMonto(Integer.parseInt(txtMonto.getText()));
        pagoActualizado.setEstado(true);
        controlador.actualizarPago(pagoAntiguo, pagoActualizado);
        setVisible(false);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        Pagos pagoEliminado = new Pagos();
        pagoEliminado.setId_pago(Integer.parseInt(txtIdPago.getText()));
        controlador.eliminarPago(pagoEliminado);
        setVisible(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        Pagos pago = new Pagos();
        pago.setId_pago(Integer.parseInt(txtIdPago.getText()));
        pago.setId_cliente(Integer.parseInt(txtIdCliente.getText()));
        pago.setId_proveedor(Integer.parseInt(txtIdProveedor.getText()));
        pago.setMonto(Integer.parseInt(txtMonto.getText()));
        pago.setEstado(true);
        controlador.agregarPago(pago);
        txtIdPago.setText("");
        txtIdCliente.setText("");
        txtIdProveedor.setText("");
        txtMonto.setText("");
        setVisible(false);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        pagoAntiguo = controlador.buscarPago(Integer.parseInt(txtBuscar.getText()));
        txtIdPago.setText(String.valueOf(pagoAntiguo.getId_pago()));
        txtIdCliente.setText(String.valueOf(pagoAntiguo.getId_cliente()));
        txtIdProveedor.setText(String.valueOf(pagoAntiguo.getId_proveedor()));
        txtMonto.setText(String.valueOf(pagoAntiguo.getMonto()));
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdPago;
    private javax.swing.JLabel lblIdProveedor;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdPago;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
