/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.brenervalladares.vista;

import java.awt.Image;
import javax.swing.JPanel;
import org.brenervalladares.modelo.Cuenta;
import org.brenervalladares.controlador.ControlDeCuenta;

/**
 *
 * @author Eduardo
 */
public class VistaCuenta extends javax.swing.JInternalFrame {
    private Image imagenDeFondo; 
    ControlDeCuenta controlador = new ControlDeCuenta();
    Cuenta cuentaAntigua = new Cuenta();
    Cuenta cuentaActualizada = new Cuenta();
    Cuenta cuentaEliminada = new Cuenta();
    
    /**
     * Creates new form Agregar
     */
    public VistaCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVistaCuenta = new PanelDeImagen(imagenDeFondo);
        lblICuenta = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblMoneda = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtMoneda = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtIdCuenta = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblICuenta.setForeground(new java.awt.Color(0, 0, 0));
        lblICuenta.setText("Id");

        lblNumero.setForeground(new java.awt.Color(0, 0, 0));
        lblNumero.setText("Numero ");

        lblTipo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo.setText("Tipo");

        lblMoneda.setForeground(new java.awt.Color(0, 0, 0));
        lblMoneda.setText("Moneda");

        lblSaldo.setForeground(new java.awt.Color(0, 0, 0));
        lblSaldo.setText("Saldo");

        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Cliente");

        txtMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonedaActionPerformed(evt);
            }
        });

        txtIdCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCuentaActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVistaCuentaLayout = new javax.swing.GroupLayout(panelVistaCuenta);
        panelVistaCuenta.setLayout(panelVistaCuentaLayout);
        panelVistaCuentaLayout.setHorizontalGroup(
            panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVistaCuentaLayout.createSequentialGroup()
                .addGroup(panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVistaCuentaLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSaldo)
                                .addComponent(lblMoneda)
                                .addComponent(lblTipo)
                                .addComponent(lblNumero)
                                .addComponent(lblICuenta)
                                .addComponent(lblNombre))
                            .addGroup(panelVistaCuentaLayout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(37, 37, 37)))
                        .addGroup(panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVistaCuentaLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdCuenta)
                                    .addComponent(txtNumero)
                                    .addComponent(txtTipo)
                                    .addComponent(txtMoneda)
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtNombre)))
                            .addGroup(panelVistaCuentaLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnActualizar)
                                .addGap(48, 48, 48)
                                .addComponent(btnEliminar))))
                    .addGroup(panelVistaCuentaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        panelVistaCuentaLayout.setVerticalGroup(
            panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVistaCuentaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addGap(55, 55, 55)
                .addGroup(panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblICuenta)
                    .addComponent(txtIdCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipo)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoneda)
                    .addComponent(txtMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldo)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(panelVistaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVistaCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVistaCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        cuentaAntigua = controlador.buscarCuenta(Integer.parseInt(txtBuscar.getText()));
        txtIdCuenta.setText(String.valueOf(cuentaAntigua.getId_cuenta()));
        txtNombre.setText(cuentaAntigua.getNombre());
        txtNumero.setText(String.valueOf(cuentaAntigua.getNumero()));
        txtTipo.setText(cuentaAntigua.getTipo());
        txtMoneda.setText(cuentaAntigua.getMoneda());
        txtSaldo.setText(String.valueOf(cuentaAntigua.getSaldo()));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        Cuenta cuenta = new Cuenta();
        cuenta.setId_cuenta(Integer.parseInt(txtIdCuenta.getText()));
        cuenta.setNombre(txtNombre.getText());
        cuenta.setNumero(Integer.parseInt(txtNumero.getText()));
        cuenta.setTipo(txtTipo.getText());
        cuenta.setMoneda(txtMoneda.getText());
        cuenta.setSaldo(Integer.parseInt(txtSaldo.getText()));
        cuenta.setEstado(true);

        controlador.agregarCuenta(cuenta);

        txtIdCuenta.setText("");
        txtNombre.setText("");
        txtNumero.setText("");
        txtTipo.setText("");
        txtMoneda.setText("");
        txtSaldo.setText("");

        setVisible(false);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        cuentaEliminada.setId_cuenta(Integer.parseInt(txtIdCuenta.getText()));
        controlador.eliminarCuenta(cuentaEliminada);
        setVisible(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        cuentaActualizada.setId_cuenta(Integer.parseInt(txtIdCuenta.getText()));
        cuentaActualizada.setNombre(txtNombre.getText());
        cuentaActualizada.setNumero(Integer.parseInt(txtNumero.getText()));
        cuentaActualizada.setTipo(txtTipo.getText());
        cuentaActualizada.setMoneda(txtMoneda.getText());
        cuentaActualizada.setSaldo(Integer.parseInt(txtSaldo.getText()));
        cuentaActualizada.setEstado(true);
        controlador.actualizarCuenta(cuentaAntigua, cuentaActualizada);
        setVisible(false);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtIdCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCuentaActionPerformed

    private void txtMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonedaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel lblICuenta;
    private javax.swing.JLabel lblMoneda;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel panelVistaCuenta;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIdCuenta;
    private javax.swing.JTextField txtMoneda;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables

    private static class PanelDeImagen extends JPanel {

        public PanelDeImagen(Image imagenDeFondo) {
        }
    }
}
